language: php

dist: 'trusty'

php:
  - '7.2'
  - '7.3'
  - '7.4'

cache:
  directories:
    - $HOME/.composer/cache

install:
  - composer install

script: 
  - vendor/bin/phpunit
  - vendor/bin/phpstan analyze --no-progress --level=1 src/
